repos:
    - repo: https://github.com/python-poetry/poetry
      rev: "1.3.0"
      hooks:
          - id: poetry-export
            args: ["-f", "requirements.txt", "-o", "requirements.txt"]
            verbose: true
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: "v2.0.2"
      hooks:
          - id: autopep8
