name: 添加机器人为好友
description: 让机器人添加你为好友。
title: "[NEW]: 添加好友"
labels: ["new"]
assignees:
  - Teahouse-Studios/akaribot-admin
body:
  - type: markdown
    attributes:
      value: |
        感谢您使用小可。原则上，非开发者不得将小可加为好友，但由于部分命令需要私聊使用，故开放此申请。
        
        若您有特殊需求，必须要让小可与您加为好友，请填写下方的表单。申请提交后，我们将会在 24 小时内进行处理。
        
        另请注意，我们可能会要求您提交更多信息。因此，请关注您的 GitHub 绑定邮箱通知。若您未在 24 小时内回复我们的要求，我们将关闭您的申请，不过您还可以再次提交。
  - type: checkboxes
    id: preflight
    attributes:
      label: 开始之前……
      description: 让我们看看你的登机牌准备好了吗
      options:
        - label: 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
          required: true
        - label: 我有必须在私聊使用机器人服务的需求。
          required: true
  - type: markdown
    attributes:
      value: |
        我们知道您不想阅读冗长的服务条款，但仍请您特别注意：
        - 您不得在使用本服务时利用提供的功能或漏洞，直接或间接地诱导小可发送违反法律法规、欺诈、虚假或产生误导的信息。
        - 无论小可是否处于运行状态，都不得对小可进行言论攻击、滥用服务以及无故禁言、踢出等不友善行为。
          - 我们会根据实际情况自行裁定不友善行为，并不限于此处列出的类型。
        - 不得利用漏洞或使用相关工具对服务器进行攻击，如发现应及时向我们报告。
        - 您不得规避本服务的任何访问或可用性限制。不得侵犯他人的权利。
        - 您不得帮助他人违反这些规则。
        
        对于任何违反上述协议、或是由我们判定为出现其它不合适的行为，我们将视情况终止对您的服务，并有权利公开相关的不良行为。
        
        请注意：上述提示不能视为对服务条款的替代。
  - type: input
    id: user-id
    attributes:
      label: 用户 ID
      description: 您的 QQ 号。
      placeholder: e.g. QQ 10000
    validations:
      required: true
  - type: input
    id: group-id
    attributes:
      label: 群组 ID
      description: 您所在的拥有小可的群组的 QQ 群号。
      placeholder: e.g. QQ 1000000
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: 理由
      description: 您需要私聊使用机器人的原因。
    validations:
      required: true
  - type: textarea
    id: group-key
    attributes:
      label: 加好友方式
      description: 您是否有特殊的验证答案？请将它们备注至此。注：您的验证答案将在申请完成后被删除。请放心填写。
      value: 加我为好友无须特殊验证答案。
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 备注
      description: 您还想告诉我们什么？
      placeholder: 什么都可以哦，没有就算了吧。
    validations:
      required: false
