from core.builtins.session.features import Features

features = Features(
    support_image=True,
    support_audio=True,
    support_video=False,
    support_mention=False,
    support_embed=True,
    support_delete=True,
    support_manage=False,
    support_permission_group=False,
    support_markdown=True,
    support_markdown_table=False,
    support_reaction=True,
    support_quote=False,
    support_rss=False,
    support_typing=True,
    support_wait=True,
    support_handle_message_nodes=True,
    support_private_msg=True,
    support_action_text=True,
    support_button=True,
    support_markdown_toggle=True,
    use_url_md_format=True,
    require_enable_modules=False,
)
