from core.elements import MessageSession


class Template:
    async def sendMessage(self, msg: MessageSession, msgchain, quote=True): ...
    async def waitConfirm(self, msg: MessageSession): ...
    def asDisplay(self, msg: MessageSession): ...
    async def revokeMessage(self, send_msg): ...
    def checkPermission(self, msg: MessageSession): ...
    class Typing:
        def __init__(self, msg: MessageSession): ...
