# https://toml.io/ja/v1.0.0
# 注：TOMLは Python ではないので、ここでは Python の文法を使わないでください。
# 例：TOML のブール値は小文字でなければならないです。

[bot_kook]
# 平台端的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = false # このプラットフォームを有効にするかどうか。

[bot_kook_secret]
# 平台端的密钥配置部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
kook_token = "<Replace me with str value>" # KOOK 机器人令牌。
