# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字である必要があります。

[module_bind]
# モジュールの設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
enable_bind_auto = false # 是否开启“bind auto”自动配对同一场景内的其他机器人。此功能为多个机器人共处同一场景的情形预留，关闭后相关命令与提示均不出现。
