# https://toml.io/ja/v1.0.0
# 注：TOMLは Python ではないので、ここでは Python の文法を使わないでください。
# 例：TOML のブール値は小文字でなければならないです。

[module_wordle]
# 模块的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
wordle_disable_image = false # wordle 模块是否禁用图片。
