# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。請不要在此處使用 Python 語法。
# 例如：TOML 中的布林值必須是小寫。

[module_ncmusic_secret]
# 模組的金鑰設定部分，此處的值若意外出現在傳送的訊息中，機器人會嘗試攔截。但請務必提防洩漏。
ncmusic_api = "<Replace me with str value>" # 網易雲音樂 API 的 API 位址。（用於 ncmusic 模組）

[module_ncmusic]
# 模組的設定部分，此處填寫的值可在訊息中以明文顯示。請不要在此部分填寫敏感資訊。
ncmusic_enable_card = false # ncmusic 模組是否啟用卡片訊息。（僅在 QQ 用戶端有效）
