# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。請不要在此處使用 Python 語法。
# 例如：TOML 中的布林值必須是小寫。

[module_bind]
# 模組的組態部分，此處填寫的值可在訊息中以明文顯示。請不要在此部分填寫敏感資訊。
enable_bind_auto = false # 是否开启“bind auto”自动配对同一场景内的其他机器人。此功能为多个机器人共处同一场景的情形预留，关闭后相关命令与提示均不出现。
