# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[bot_matrix]
# The basic config section of the platform. The value ​​filled in here can be displayed in the message. Please do not fill in sensitive information in this section.
enable = false # Whether to enable this platform.
matrix_homeserver = "https://matrix.org" # Matrix bot homeserver.
matrix_user = "@akaribot:matrix.org" # Matrix bot fully restricted user ID.
matrix_device_name = "<Replace me with str value>" # Matrix bot device name, it can be filled in at will.

[bot_matrix_secret]
# The secret config section of the platform. The bot will try to intercept if the value here accidentally appears in the message sent, but be careful to prevent leakage.
matrix_device_id = "<Replace me with str value>" # Matrix bot device ID.
matrix_token = "<Replace me with str value>" # Matrix bot token.
matrix_megolm_backup_passphrase = "<Replace me with str value>" # Matrix bot's Megolm backup passphrase.
