# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[module_ncmusic_secret]
# The secret config section of the module. The bot will try to intercept if the value here accidentally appears in the message sent, but be careful to prevent leakage.
ncmusic_api = "<Replace me with str value>" # API address of NetEase Cloud Music API. (For ncmusic module)

[module_ncmusic]
# The basic config section of the module. The value ​​filled in here can be displayed in the message. Please do not fill in sensitive information in this section.
ncmusic_enable_card = false # Whether enables card messages of ncmusic module. (Only valid on QQ client)
