# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[s3]
# The basic config section of the S3-compatible API. The values entered here can be displayed in the message. Please do not enter sensitive information in this section.
s3_endpoint_url = "<Replace me with str value>" # S3-compatible API endpoint URL.
s3_bucket = "<Replace me with str value>" # S3-compatible API bucket name.
s3_region = "us-east-1" # S3-compatible API region name.
s3_public_endpoint = "<Replace me with str value>" # S3-compatible API public access URL.
s3_internal_endpoint = "<Replace me with str value>" # S3-compatible API internal access URL.
s3_temp_max_count = 20 # Maximum number of temporary files for the S3-compatible API.

[s3_secret]
# The secret config section of the S3-compatible API. The bot will try to intercept if the values here accidentally appears in the message sent, but be careful to prevent leakage.
s3_access_key = "<Replace me with str value>" # S3-compatible API AccessKey.
s3_secret_key = "<Replace me with str value>" # S3-compatible API SecretKey.
