# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[s3]
# {I18N:config.table.config_s3}
s3_endpoint_url = "<Replace me with str value>" # S3 兼容 API 的 Endpoint URL。
s3_bucket = "<Replace me with str value>" # S3 兼容 API 的 Bucket 名。
s3_region = "us-east-1" # S3 兼容 API 的地域名。
s3_public_endpoint = "<Replace me with str value>" # S3 兼容 API 的公网访问 URL。
s3_internal_endpoint = "<Replace me with str value>" # S3 兼容 API 的内网访问 URL。
s3_temp_max_count = 20 # S3 兼容 API 的临时文件最大数量。

[s3_secret]
# {I18N:config.table.secret_s3}
s3_access_key = "<Replace me with str value>" # {I18N:config.comments.s3_secret.s3_access_key}
s3_secret_key = "<Replace me with str value>" # {I18N:config.comments.s3_secret.s3_secret_key}
