# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[bot_matrix]
# 平台端的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = false # 是否启用此平台。
matrix_homeserver = "https://matrix.org" # Matrix 机器人的家服务器。
matrix_user = "@akaribot:matrix.org" # Matrix 机器人的完全限定用户 ID。
matrix_device_name = "<Replace me with str value>" # Matrix 机器人的设备名称，可随意填写。

[bot_matrix_secret]
# 平台端的密钥配置部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
matrix_device_id = "<Replace me with str value>" # Matrix 机器人设备 ID。
matrix_token = "<Replace me with str value>" # Matrix 机器人令牌。
matrix_megolm_backup_passphrase = "<Replace me with str value>" # Matrix 机器人的 Megolm 备份密码短语。
