# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[bot_onebot]
# 客户端的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = false # 是否开启此客户端。
qq_host = "127.0.0.1:8080" # WebSocket 主服务器的地址。（OneBot 协议端请使用反向 WebSocket 方式进行连接）
qq_enable_listening_self_message = false # 使用 OneBot 协议时，是否开启自身消息监听。
qq_enable_temp_session = false # 使用 OneBot 协议时，是否开启临时会话。
qq_allow_approve_friend = false # 使用 OneBot 协议时，是否自动同意好友请求。
qq_allow_approve_group_invite = false # 使用 OneBot 协议时，是否自动同意群邀请。
qq_typing_emoji = 181 # 使用 OneBot 协议时，正在处理消息时向消息挂上的回应表情 ID，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api-v2/openapi/emoji/model.html#Emoji
qq_limited_emoji = 10060 # 使用 OneBot 协议时，消息处理失败时向消息挂上的回应表情 ID，需协议端支持。ID 详见：https://bot.q.qq.com/wiki/develop/api-v2/openapi/emoji/model.html#Emoji
qq_initiative_msg_cooldown = 10 # 限制主动消息发送的冷却时间，单位为秒。

[bot_onebot_secret]
# 客户端的密钥配置部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
qq_access_token = "<Replace me with str value>" # {I18N:config.comments.bot_onebot_secret.qq_access_token}
