# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[module_coin]
# 模块的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
coin_limit = 10000 # coin 模块可抛硬币的上限。
coin_faceup_weight = 4997 # coin 模块抛硬币时正面的权重。
coin_facedown_weight = 4997 # coin 模块抛硬币时反面的权重。
coin_stand_weight = 6 # coin 模块抛硬币时立起的权重。
