# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[smtp]
# SMTP 的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = false # 是否开启 SMTP 邮件上报，开启后将不再上报至场景。
smtp_host = "<Replace me with str value>" # SMTP 服务器地址。
smtp_port = 587 # SMTP 服务器端口号。
smtp_username = "<Replace me with str value>" # SMTP 登录用户名。
smtp_sender = "<Replace me with str value>" # 发件人地址，留空则使用登录用户名。
smtp_ssl = false # 是否使用 SMTPS（SSL）连线。
smtp_starttls = true # 是否启用 STARTTLS。

[smtp_secret]
# SMTP 的密钥部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
smtp_password = "<Replace me with str value>" # SMTP 登录密码。
smtp_recipients = [] # 邮件上报收件人清单。
