# https://toml.io/ko/v1.0.0
# 주의: TOML은 Python이 아닙니다. Python 문법을 사용하지 마십시오.
# 예: TOML의 불리언 값은 반드시 소문자로 작성해야 합니다.

[bot_onebot]
# 클라이언트 구성 섹션입니다. 여기에 입력한 값은 메시지에 일반 텍스트로 표시됩니다. 민감한 정보는 이 섹션에 입력하지 마십시오.
enable = false # 이 클라이언트를 활성화할지 여부.
qq_host = "127.0.0.1:8080" # WebSocket 메인 서버의 주소입니다. (OneBot 프로토콜 사용 시 역방향 WebSocket 방식으로 연결해 주십시오)
qq_enable_listening_self_message = false # OneBot 프로토콜을 사용할 때, 자체 메시지 수신 기능을 활성화할지 여부.
qq_enable_temp_session = false # OneBot 프로토콜을 사용할 때 임시 세션을 활성화할지 여부.
qq_allow_approve_friend = false # OneBot 프로토콜을 사용할 때 친구 요청을 자동으로 수락할지 여부.
qq_allow_approve_group_invite = false # OneBot 프로토콜을 사용할 때 그룹 초대를 자동으로 수락할지 여부.
qq_typing_emoji = 181 # OneBot 프로토콜을 사용할 때, 이는 메시지 처리 중에 메시지에 첨부되는 응답 이모티콘 ID를 의미합니다. 프로토콜 지원이 필요합니다. ID는 다음을 참조하십시오: https://bot.q.qq.com/wiki/develop/api-v2/openapi/emoji/model.html#Emoji
qq_limited_emoji = 10060 # OneBot 프로토콜을 사용할 때, 메시지 처리가 실패하면 메시지에 추가되는 응답 이모티콘 ID입니다. 프로토콜 지원이 필요합니다. ID는 다음을 참조하십시오: https://bot.q.qq.com/wiki/develop/api-v2/openapi/emoji/model.html#Emoji
qq_initiative_msg_cooldown = 10 # 능동 메시지 전송 대기 시간을 제한합니다. 단위는 초입니다.

[bot_onebot_secret]
# 클라이언트 키 설정 섹션입니다. 이 값이 전송된 메시지에 실수로 나타날 경우 봇이 해당 메시지를 가로채려고 시도합니다. 하지만 이 값이 유출되지 않도록 각별히 주의해 주십시오.
qq_access_token = "<Replace me with str value>" # 使用 OneBot 协议时，连接 WebSocket 服务器的 Access Token。
