# https://toml.io/ko/v1.0.0
# 주의: TOML은 Python이 아닙니다. Python 문법을 사용하지 마십시오.
# 예: TOML의 불리언 값은 반드시 소문자로 작성해야 합니다.

[bot_matrix]
# 클라이언트 구성 섹션입니다. 여기에 입력한 값은 메시지에 일반 텍스트로 표시됩니다. 민감한 정보는 이 섹션에 입력하지 마십시오.
enable = false # 플랫폼 활성화 여부.
matrix_homeserver = "https://matrix.org" # Matrix 봇의 홈 서버.
matrix_user = "@akaribot:matrix.org" # Matrix 봇의 전체 사용자 ID.
matrix_device_name = "<Replace me with str value>" # Matrix 봇의 기기 이름. 원하는 대로 입력할 수 있습니다.

[bot_matrix_secret]
# 클라이언트 키 설정 섹션입니다. 이 값이 전송된 메시지에 실수로 나타날 경우 봇이 해당 메시지를 가로채려고 시도합니다. 하지만 이 값이 유출되지 않도록 각별히 주의해 주십시오.
matrix_device_id = "<Replace me with str value>" # Matrix 봇 기기 ID.
matrix_token = "<Replace me with str value>" # Matrix 봇 토큰.
matrix_megolm_backup_passphrase = "<Replace me with str value>" # Matrix 봇의 Megolm 백업 암호.
