# https://toml.io/ko/v1.0.0
# 주의: TOML은 Python이 아닙니다. Python 문법을 사용하지 마십시오.
# 예: TOML의 불리언 값은 반드시 소문자로 작성해야 합니다.

[module_ai]
# 모듈의 구성 섹션입니다. 여기에 입력한 값은 메시지에 일반 텍스트로 표시됩니다. 민감한 정보는 이 섹션에 입력하지 마십시오.
llm_max_tokens = 2048 # LLM의 토큰 수 상한을 설정합니다.
llm_timeout = 60 # LLM 시간 초과.
llm_temperature = 1 # LLM의 온도 샘플링. 범위는 0에서 2 사이입니다. top_p와 동시에 변경하는 것은 권장하지 않습니다.
llm_top_p = 1 # LLM의 핵 샘플링. 범위는 0에서 1 사이입니다. temperature와 동시에 수정하는 것은 권장하지 않습니다.
llm_frequency_penalty = 0 # LLM의 빈도 페널티. 범위는 -2에서 2 사이입니다.
llm_presence_penalty = 0 # LLM의 존재 페널티. 범위는 -2에서 2 사이입니다.
ai_default_llm = "<Replace me with str value>" # 기본으로 사용되는 LLM.

[module_ai_secret]
# 모듈의 키 설정 섹션입니다. 이 값이 전송된 메시지에 실수로 나타날 경우 봇이 해당 메시지를 가로채려고 시도합니다. 하지만 이 값이 유출되지 않도록 각별히 주의해 주십시오.
e2b_api_key = "<Replace me with str value>" # E2B API 키.
