name: Update Version File

on:
  push:
    branches:
      - master

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get current version
      id: get_version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
    
    - name: Write File
      run: echo "${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.commit_hash }}" > ./bots/aiocqhttp/assets/version
      
    - name: Commit & Push
      uses: ludeeus/action-push@0.0.1
      env:
        ACTION_MAIL: "silian_zheng@outlook.com"
        ACTION_NAME: "SilianZ"
        ACTION_BRANCH: "master"
        ACTION_MESSAGE: "Update version file"
        secrets: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      

