name: Update Version

on:
  push:
    branches:
      - master

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
    
    - name: Write File
      run: echo "Akari-bot-v4.0.11+${{ steps.get_commit_hash.outputs.commit_hash }}" > ./bots/aiocqhttp/assets/version
      
    - name: Commit files
      run: |
        git config --local user.name "SilianZ"
        git config --local user.password "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        git commit -a -m "Add changes"
        git push

