name: Update Version

on:
  push:
    branches:
      - master

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get current version
      id: get_version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
    
    - name: Write File
      run: echo "${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.commit_hash }}" > ./bots/aiocqhttp/assets/version
      
    - name: Commit files
      run: |
        git config --global user.email "silian_zheng@outlook.com"
        git config --global user.name "SilianZ"
        git config --global user.password "${{ secret.PERSONAL_ACCESS_TOKEN }}"
        git commit -a -m "Add changes"
    
    - name: Push files
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}

