name: Update Version

on:
  push:
    branches:
      - master

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Write File
      run: |
        version="Akari-bot-${{ GITHUB_REF#refs/heads/ }}"
        commit_hash="${{ github.commit_hash }}"

        echo "$version" > ./bots/aiocqhttp/assets/version_tag
        echo "$commit_hash" > ./bots/aiocqhttp/assets/version

        echo "$version" > ./bots/aiogram/assets/version_tag
        echo "$commit_hash" > ./bots/aiogram/assets/version

        echo "$version" > ./bots/discord/assets/version_tag
        echo "$commit_hash" > ./bots/discord/assets/version

        echo "$version" > ./bots/kook/assets/version_tag
        echo "$commit_hash" > ./bots/kook/assets/version

        echo "$version" > ./bots/matrix/assets/version_tag
        echo "$commit_hash" > ./bots/matrix/assets/version

        echo "$version" > ./assets/version_tag
        echo "$commit_hash" > ./assets/version
      
    - name: Commit files
      run: |
        git config --local user.name "Akari-bot"
        git commit -a -m "Add changes"
        git push

