name: Update Version File

on:
  push:
    branches:
      - master

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get current version
      id: get_version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Write version to file
      run: echo "${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.commit_hash }}" > ./bots/aiocqhttp/assets/version

    - name: Configure Git
      run: |
        git config --global user.name "SilianZ"
        git config --global user.email "silian_zheng@outlook.com"
        if ! git config --get http.https://github.com/.extraheader | grep -q "Authorization"; then
          git config --global --add http.https://github.com/.extraheader "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        fi
        
    - name: Commit and push updated version file
      run: |
        git add -f ./bots/aiocqhttp/assets/version
        git commit -m "Update version in ./bots/aiocqhttp/assets/version"
        git push
