name: Update Version

on:
  push:
    branches:
      - master

jobs:
  update_version_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
    
    - name: Write File
      run: |
        version="Akari-bot-${{ github.ref }}"
        commit_hash="${{ steps.get_commit_hash.outputs.commit_hash }}"

        echo "$version" > ./bots/aiocqhttp/assets/version_tag
        echo "$commit_hash" > ./bots/aiocqhttp/assets/version

        echo "$version" > ./bots/aiogram/assets/version_tag
        echo "$commit_hash" > ./bots/aiogram/assets/version

        echo "$version" > ./bots/discord/assets/version_tag
        echo "$commit_hash" > ./bots/discord/assets/version

        echo "$version" > ./bots/kook/assets/version_tag
        echo "$commit_hash" > ./bots/kook/assets/version

        echo "$version" > ./bots/matrix/assets/version_tag
        echo "$commit_hash" > ./bots/matrix/assets/version

        echo "$version" > ./assets/version_tag
        echo "$commit_hash" > ./assets/version
      
    - name: Commit files
      run: |
        git config --local user.name "Akari-bot"
        git config --local user.password "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        git commit -a -m "Add changes"
        git push

