name: "WebUI Build and Sync (Weekly, UTC)"

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync-webui:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout WebUI repo
        uses: actions/checkout@v4
        with:
          ref: beta
          repository: DoroWolf/akari-bot-webui
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: |
          npm install
          npm run build
  
      - name: Compare webui directories
        run: |
          if diff -r dist ./webui; then
            echo "No changes detected between webui directories. Skipping commit."
            exit 0
          fi
  
      - name: Move dist to webui directory
        run: |
          rsync -av --remove-source-files dist/ ./webui/
  
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull origin master
          git add .
          git commit -m "Sync WebUI [skip ci]"
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
